### ISSUE TITLE
Logo Beta n'apparait pas sur la page principale

### ISSUE THREAD

**Issue by pli01** [LAB-MI/candilib#115]
Logo Beta n'apparait pas sur la page principale.
Seul le texte est présent.

**Comment by baudointran** [comment]
il faut ajouter dans le conf de nginx (nginx.conf ou nginx.template ):
add_header Content-Security-Policy "default-src https: 'self' 'unsafe-inline' 'unsafe-eval' data: ;";

En théorie c'est 
add_header Content-Security-Policy "img-src https: 'self' data: ;";
Mais ce n'est pas supporté par chrome
Pas fait de test sur edge ni sur safari

**Comment by baudointran** [comment]
corrigé sur la branch correction_v1.0.1 en attendant la v2

**Comment by pli01** [comment]
mergé dans https://github.com/LAB-MI/candilib/tree/tech/split-client-server-clean
